### ISSUE TITLE
无法编译代码

### ISSUE THREAD

**Issue by tianshaokai** [lizihanglove/NewBee#1]
![image](https://user-images.githubusercontent.com/6706496/43145598-331abaf0-8f92-11e8-8212-c47683aa2793.png)

**Comment by lizihanglove** [comment]
@tianshaokai  你能不能提供更多信息，我再看一下问题所在。

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/43400863-63af7076-9441-11e8-8697-992089534136.png)

**Comment by tianshaokai** [comment]
support fragment 指向的地址不对，不知道怎么回事

**Comment by lizihanglove** [comment]
@tianshaokai  你把你的as kotlin插件更新一下，应该就好了。

**Comment by tianshaokai** [comment]
我的stuido 是3.0.1 默认安装的kotlin 插件，你知道除了不升级stuido 怎么升级插件啊

**Comment by tianshaokai** [comment]
我现在的版本对应的是1.1.51这个版本

**Comment by lizihanglove** [comment]
@tianshaokai Alt+Ctrl+S 进入AS设置界面，点击Plugins,在搜索框中搜索kotlin，就能够更新了。如果已经是最新，你试着Clean一下，不行再联系我。

**Comment by tianshaokai** [comment]
@lizihanglove  我试了，kotlin 不能更新，你的studio 是多少版本， 能不能加你个联系方式啊，交流一下kotlin开发

**Comment by lizihanglove** [comment]
@tianshaokai 你加我QQ吧，1396981248
